### ISSUE TITLE
PreRelease: Submitting issues

### ISSUE THREAD

**Issue by nmueller18** [ISAAKiel/mortAAR#28]
I have finally submitted `mortAAR` to CRAN! However, I got it back with comments (see below). Actually, I am not sure what CRAN is expecting from us (especially concerning the "small executables").

Thanks, please elaborate the provided functionality in the description field.

Can you provide a reference in the 'Description' field of your DESCRIPTION file? If so, please write the reference in the form
authors (year) <doi:...>
authors (year) <arXiv:...>
authors (year) <http:...> (if doi/arXiv not available)
authors (year) <https:...> (if doi/arXiv not available)
authors (year, ISBN:...)
with no space after 'doi:', 'arXiv:', 'http:', 'https:' and angle brackets for auto-linking.

Please add more small executable examples in your Rd-files.
Something like
\examples{
      examples for users:
      executable in < 5 sec
      for checks
      \dontshow{
             examples for checks:
             executable in < 5 sec together with the examples above
             not shown to users
      }
      donttest{
             further examples for users (not used for checks)
      }
}
would be desirable.

Please do not comment out examples.

Please fix and resubmit.

**Comment by nevrome** [comment]
1. Description
We can't provide a single reference in the description, because the algorithms are based on several different sources. That's already documented elsewhere. What we can and should do is increasing the length of the description. It can be more speaking.

2. Examples
It's a valid point: Some functions only contain [dummy lines](https://github.com/ISAAKiel/mortAAR/blob/19379c06866adac77a62c0c3737b81abe163f3f4/R/output_functions.R#L12-L13) in the example field.
First of all I suggest to [hide](https://stackoverflow.com/questions/15892761/do-not-show-function-help-document-in-building-r-package-by-roxygen2) some of the internal functions from the documentation. Then we can easily add some more examples with the above mentioned check hierarchy for the few functions that actually are available to the end user. 

I can care for 2. if you deal with 1., @nmueller18. What do you think?

**Comment by nmueller18** [comment]
That's fair enough.

**Comment by nevrome** [comment]
I restructured the documentation and added some (reasonably uniform) example code for all relevant functions. @nmueller18 Please take a look at the package help page index and tell me what you think. I think we can give it another try.

**Comment by nmueller18** [comment]
In the document of the function `Life table`two instances of "## Not run:" and "## End(Not run)" appear. Is this correct?

**Comment by nevrome** [comment]
It was intended like this, but I thought about it again and decided to remove it. The chunk is now also regular example code.

**Comment by nmueller18** [comment]
Resubmission in process!

**Comment by nevrome** [comment]
Any feedback so far concerning the example code?
